apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-web-config
  namespace: app
data:
  # 前端配置
  REACT_APP_API_URL: "/api"
  REACT_APP_TITLE: "CRM后端管理系统"
  REACT_APP_ENV: "production"
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_COMPANY: "CRM Corp"
  
  # 后端服务地址（供前端 JS 读取）
  config.js: |
    window.APP_CONFIG = {
      API_BASE_URL: "/api",
      CRM_SERVICE: "http://crm-service.app:8080",
      ENV: "production",
      VERSION: "1.0.0"
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-web
  namespace: app
  labels:
    app: crm-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crm-web
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: crm-web-config
          items:
          - key: config.js
            path: config.js
      containers:
      - name: crm-web
        image: crm-web:1.0.0-amd64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: crm-web-config
              key: REACT_APP_API_URL
        - name: REACT_APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: crm-web-config
              key: REACT_APP_TITLE
        - name: REACT_APP_ENV
          valueFrom:
            configMapKeyRef:
              name: crm-web-config
              key: REACT_APP_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: crm-web-service
  namespace: app
spec:
  selector:
    app: crm-web
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-web-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: crm.local
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: crm-service
            port:
              number: 8080
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: crm-web-service
            port:
              number: 80