apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: app
data:
  APPLICATION_ENV: "production"
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: app
  labels:
    app: crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm
        image: crm:1.0.4-amd64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080  # 修正为 8080，与应用实际端口一致
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: crm-config
              key: SPRING_PROFILES_ACTIVE
        # 数据库连接配置
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service.db.svc.cluster.local:3306/crm?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-app
              key: password
        # Redis 连接配置
        - name: SPRING_REDIS_HOST
          value: "redis-service.db.svc.cluster.local"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_PASSWORD
          value: "redis123"
        # RabbitMQ 连接配置
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service.db.svc.cluster.local"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service
  namespace: app
spec:
  selector:
    app: crm
  ports:
  - port: 8080        # Service 端口
    targetPort: 8080  # 目标端口（容器端口），修正为 8088
    nodePort: 30080   # NodePort，可以保持 30088 或改为其他端口
  type: NodePort
