apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
  namespace: db
spec:
  type: NodePort
  selector:
    app: rabbitmq  # 需要根据你的Pod标签调整
  ports:
  - name: management
    port: 15672
    targetPort: 15672
