apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: db
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379  # 范围 30000-32767
  type: NodePort