#user  nobody;                   #表示当系统在执行worker进程的时候由哪个用户去执行，（默认为nobody）
worker_processes  10;            #逻辑CPU的个数设置的值为：（n-1）

 # nginx的日志级别：debug info notice warn error crit 等级逐渐升高。

#error_log  logs/error.log;      #错误的日志，在编译的时候已经设置相关的路径。
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    #默认使用epoll
    use epoll;
    #每个worker允许的客端最大连接数
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

}